name: Shorebird Patch

on:
  push:
    branches: [shorebird]

jobs:
  patch:
    runs-on: ubuntu-latest
    env:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: Shorebird Patch Android
        uses: shorebirdtech/shorebird-patch@v1
        with:
          platform: android
          release-version: latest
          args: --allow-asset-diffs
